##===- lib/Transforms/Hello/Makefile -----------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##

LEVEL = ../../..
LIBRARYNAME = FindBoundary
#CPPFLAGS+=-I../reliability -I../RunTimeMonitors -I../MyUtils -I../spec_pipeline
CPPFLAGS+=-I../reliability -I../MyUtils -I../RunTimeMonitors -I../spec_pipeline
LOADABLE_MODULE = 1
USEDLIBS = 

include $(LEVEL)/Makefile.common

